#!/bin/bash

# Take and print the numbers between 1 and 100.
# When a number is divisible by 3, print "Fizz" instead of the number.
# When it is divisible by 5, print "Buzz" instead.
# When it is divisible both by 3 and 5, print "FizzBuzz"

num=1;

while [ $num -le 100 ]; do 

   if [ $((num % 3)) == 0 ] && [ $((num % 5)) == 0 ] ; then 
     echo "FizzBuzz ($num)"
    
   elif ! ((num % 5)); then 
     echo "Buzz ($num)"
   
   elif ! ((num % 3)); then 
     echo "Fizz ($num)"
   
   else 
     echo "$num"
  
   fi 
   
   ((num++))

done
